'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Biblioteca1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0510a72c2ec9fced913d8795e31b8c26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0510a72c2ec9fced913d8795e31b8c26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _055238fdf052f396915ae60ca435daba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("055238fdf052f396915ae60ca435daba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1105040() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1105040", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1277216() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1277216", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _14184() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("14184", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1669652() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1669652", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _201531() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("201531", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2153422() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2153422", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2153422__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2153422 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _29302() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("29302", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _29302__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("29302 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2df206a400456bde7bd40a3301241b06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2df206a400456bde7bd40a3301241b06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _37237() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("37237", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _532e26143a0435e9c6ca7f436474389f_icono_de_libros_by_vexels() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("532e26143a0435e9c6ca7f436474389f-icono-de-libros-by-vexels", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _57477() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("57477", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _585e4beacb11b227491c3399() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("585e4beacb11b227491c3399", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _60710() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("60710", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _61205() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("61205", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _61225() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("61225", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _61391() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("61391", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _975793fff4eb682dcc396c2885a13f2f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("975793fff4eb682dcc396c2885a13f2f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_file() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add-file", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property borrow_book() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("borrow-book", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property depositphotos_456000314_stock_illustration_borrow_book_icon_vector_illustration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("depositphotos_456000314-stock-illustration-borrow-book-icon-vector-illustration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property descarga() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("descarga", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property descarga__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("descarga (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eye_1915454_960_720() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eye-1915454_960_720", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gratis_png_lapiz_iconos_de_computadora_dibujo_diseno_de_icono_lapiz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gratis-png-lapiz-iconos-de-computadora-dibujo-diseno-de-icono-lapiz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gratis_png_libro_abierto_libro_de_iconos_de_computadora_libro_abierto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gratis-png-libro-abierto-libro-de-iconos-de-computadora-libro-abierto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gratis_png_persona_con_pluma_iconos_de_computadora_pluma_escritura_mano_con_pluma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gratis-png-persona-con-pluma-iconos-de-computadora-pluma-escritura-mano-con-pluma"& _ 
                        "", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property istockphoto_833384844_612x612() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("istockphoto-833384844-612x612", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kisspng_computer_icons_encapsulated_postscript_arrow_downl_return_icon_5b1392788bd9d4_3830976415280093365728() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kisspng-computer-icons-encapsulated-postscript-arrow-downl-return-icon-5b1392788b"& _ 
                        "d9d4.3830976415280093365728", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kisspng_computer_icons_serach_5b28c8619603d7_4670525415293993936145() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kisspng-computer-icons-serach-5b28c8619603d7.4670525415293993936145", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kisspng_symbol_computer_icons_mission_statement_vision_sta_vision_5ac4dc94eefae1_1283963415228509649789() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kisspng-symbol-computer-icons-mission-statement-vision-sta-vision-5ac4dc94eefae1."& _ 
                        "1283963415228509649789", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_clipart_computer_icons_the_book_thief_book_angle_rectangle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png-clipart-computer-icons-the-book-thief-book-angle-rectangle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_transparent_computer_icons_book_df_dance_studio_literature_book_angle_rectangle_reading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png-transparent-computer-icons-book-df-dance-studio-literature-book-angle-rectang"& _ 
                        "le-reading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_transparent_eye_computer_icons_icon_design_eye_people_color_medical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png-transparent-eye-computer-icons-icon-design-eye-people-color-medical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property recensioni_di_libri() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("recensioni-di-libri", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property return_book() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("return-book", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property return_book1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("return-book1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UNICAES_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UNICAES_Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vector_library_building_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vector-library-building-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
